# Generated by Django 4.0.5 on 2022-06-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_certificate_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='url',
        ),
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certificate'),
        ),
    ]
